ChatbotBuilder/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('botbuilder.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path

from . import views

urlpatterns = [
     path('register', views.register, name='register'),
     path('login', views.login_, name='login'),
     path('logout', views.logout_, name='logout'),
]

botbuilder/urls.py
from django.urls import path

from . import views

app_name = 'ai_tools'

urlpatterns = [
     path('', views.chatbot_builder_home, name='home'),
     path('ajax/chatbot-form/', views.chatbot_form, name='chatbot_form'),
     path('ajax/chat/', views.chat_form, name='chat_form'),
     path('create-chatbot/', views.create_chatbot, name='create_chatbot'),
     path('ajax/customize-chatbot/', views.customize_chatbot, name='chatbot_customizations'),
     path('chatbot/response/<str:chatbot_uuid>/', views.get_chatbot_response, name='get_chatbot_response'),
     path('customize-bot/', views.customize_bot, name='customize_bot'),
     path('chatbot-settings/<str:chatbot_id>/', views.chatbot_settings, name='chatbot_settings'),
     path('train_bot', views.chatbot_train, name='train_bot'),
     path('embed.js/<str:chatbot_uuid>/', views.embed_js, name='embed_js'),
     path('get_chat_sessions/', views.get_chat_sessions, name='get_chat_sessions'),
     path('get-knowledge-base', views.get_knowledge_base, name='get_knowledge_base'),
     path('export-chatbot', views.export_chatbot, name='export_chatbot'),
     path('export-chats', views.export_chats, name='export_chats'),
     path('add-files', views.add_files, name='add_files'),
     path('delete-knowledge-base-item/', views.delete_knowledge_base_item, name='delete_knowledge_base_item'),
     path('delete_chat_session/', views.delete_chat_session, name='delete_chat_session'),
     path('delete_chatbot/', views.delete_chatbot, name='delete_chatbot'),
]

botbuilder/models.py
import uuid
from django.db import models
from django.conf import settings
from django.utils import timezone

# Create your models here.
def get_default_prompts():
    return [
        "Explain the contents of this chatbot?",
        "Name the files in your Knowledge Base",
        "How can I customize the appearance of the chatbot?"
    ]

def get_default_customization():
    return "{\"font\": \"Montserrat\", \"background_color\": \"#ebeaea\", \"font_color\": \"#ffffff\", \"input_background\": \"#e6e6e6\", \"chatbot_background_color\": \"#000000\", \"input_font_color\": \"#000000\", \"user_background_color\": \"#6e6e6e\", \"user_font_color\": \"#ffffff\", \"prompts_font_color\": \"#ffffff\", \"ai_tools_font_color\": null, \"ai_tools_border_color\": null}"

class Chatbot(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    name = models.CharField(max_length=255, unique=True)
    customization = models.JSONField(
        null=True, 
        blank=True, 
        default=get_default_customization
    )
    description = models.TextField(null=True)
    logo = models.ImageField(upload_to='chatbot_logos/', null=True, blank=True)
    custom_url = models.CharField(max_length=255, unique=True, null=True, blank=True)
    allow_prompts = models.BooleanField(default=True)
    prompts = models.JSONField(null=True, blank=True, default=get_default_prompts)
    welcome_message = models.CharField(max_length=255, null=True, blank=True, default="👋 Hi, how can I help you?")
    creativity = models.CharField(max_length=255, null=True, blank=True, default="0")
    prompt_template = models.TextField(null=True, blank=True, 
        default="""
        Your main goal is to provide answers as accurately as possible, based on the instructions and Knowledge Base you have been given.
        If a question does not match the provided Knowledge Base or chat history, do not answer it and courteously ask the user to ask questions within the context.
        Use the following pieces of information to answer the user's question.
        If you don't know the answer, just say that you don't know, don't try to make up an answer.
        """)
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='created_chatbots', on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now, editable=False)

    def __str__(self):
        return f"{self.name} - {self.creator}"

class KnowledgeBase(models.Model):
    chatbot = models.ForeignKey(Chatbot, on_delete=models.CASCADE)
    folder_path = models.CharField(max_length=255, null=True, blank=True)
    files = models.JSONField(default=dict, null=True, blank=True)
    urls = models.JSONField(default=dict, null=True, blank=True)
    created_at = models.DateTimeField(default=timezone.now, editable=False, null=True, blank=True)

    def __str__(self):
        return f"{self.chatbot} - {self.folder_path or self.url}"

class ChatSession(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    name = models.CharField(max_length=255, null=True, blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='chat_sessions', on_delete=models.CASCADE, null=True, blank=True)
    chatbot = models.ForeignKey(Chatbot, on_delete=models.CASCADE)
    chat_history = models.JSONField(default=dict, null = True, blank=True)
    created_at = models.DateTimeField(default=timezone.now, editable=False)

    def __str__(self):
        return f"{self.user} - {self.chatbot}"

botbuilder/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from .models import Chatbot, KnowledgeBase, ChatSession
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse, HttpResponseForbidden, Http404
from django.shortcuts import get_object_or_404
from .models import *
import json
import os
from django.urls import reverse
from django.middleware.csrf import get_token
from bs4 import BeautifulSoup
import requests
from .utils import *
import zipfile
from io import BytesIO, StringIO
import shutil
import pandas as pd

@login_required(login_url='login')
def ai_tools_home(request):
    return render(request, 'ai_tools/ai_tools_home.html')
    
@login_required(login_url='login')
def chatbot_builder_home(request):
    # Filter chatbots by the logged-in user
    chatbots = Chatbot.objects.filter(creator=request.user if request.user.is_authenticated else None)
    return render(request, 'ai_tools/chatbot_builder_home.html', {'chatbots': chatbots})

def photo_generator_home(request):
    return render(request, 'ai_tools/photo_generator_home.html')


@login_required(login_url='login')
def create_chatbot(request):
    if request.method == 'POST':
        uploaded_at = timezone.now()
        uploaded_at_str = uploaded_at.isoformat()
        uploaded_files = []
        name = request.POST.get('name')
        description = request.POST.get('description')
        if Chatbot.objects.filter(name=name).exists():
            return JsonResponse({'status': 'error', 'message': "Chatbot's Name Already Taken"}, status=500)
        if not description:
            description = "A dummy description"
        chatbot_dir = os.path.join("media", "chatbot", name, "data")
        file_info = []
        if 'file[0]' in request.FILES and request.FILES['file[0]']:
            os.makedirs(chatbot_dir, exist_ok=True)
            if request.FILES.keys():
                for key in request.FILES.keys():
                    if key.startswith('file['):
                        uploaded_files.append(request.FILES[key])

                for uploaded_file in uploaded_files:
                    file_path = os.path.join(chatbot_dir, uploaded_file.name)
                    with open(file_path, 'wb') as f:
                        for chunk in uploaded_file.chunks():
                            f.write(chunk)
                    file_info.append({'filename': uploaded_file.name, 'file_path': file_path, 'uploaded_at': uploaded_at_str})
                    if uploaded_file.name.endswith('.xlsx'):
                        add_empty_row_to_excel(file_path)
                    elif uploaded_file.name.endswith('.csv'):
                        add_empty_row_to_csv(file_path)

        url_info = []
        url_input = request.POST.getlist('url_input[]', None)
        if url_input and any(url_input):
            os.makedirs(chatbot_dir, exist_ok=True)
            for url in url_input:
                if url:
                    file_paths = load_url(url, chatbot_dir)
                    for file_path in file_paths:
                        if is_google_drive_folder_url(url):
                            url_info.append({'url': file_path[0], 'file_path': file_path[1], 'uploaded_at': uploaded_at_str})
                        else:
                            url_info.append({'url': url, 'file_path': file_path, 'uploaded_at': uploaded_at_str})

        url_file = request.FILES.get('url_txt', None)
        if url_file is not None:
            os.makedirs(chatbot_dir, exist_ok=True)
            url_list = url_file.read().decode('utf-8').splitlines()
            for url in url_list:
                if url:
                    file_paths = load_url(url, chatbot_dir)
                    for file_path in file_paths:
                        if is_google_drive_folder_url(url):
                            url_info.append({'url': file_path[0], 'file_path': file_path[1], 'uploaded_at': uploaded_at_str})
                        else:
                            url_info.append({'url': url, 'file_path': file_path, 'uploaded_at': uploaded_at_str})

        if name and description:
            new_chatbot = Chatbot(
                name=name,
                description=description,
                creator=request.user
            )
            new_chatbot.save()
            if file_info == [] and url_info == []:
                return JsonResponse({'status': 'error', 'message': 'No Knowledge Files Detected.'}, status=400)
            
            knowledge_base = KnowledgeBase(
                chatbot=new_chatbot,
                folder_path=chatbot_dir,
                files=file_info,
                urls=url_info
            )
            knowledge_base.save()

            return JsonResponse({'status': 'success', 'chatbot_id': new_chatbot.id}, status=201)

        return JsonResponse({'status': 'error', 'message': 'Name is required.'}, status=400)

    return JsonResponse({'status': 'error', 'message': 'Invalid request method.'}, status=405)

def chatbot_form(request):
    return render(request, 'ai_tools/create_chatbot_form.html')

def customize_chatbot(request):
    chatbot_uuid = request.GET.get('chatbot_uuid')
    chatbot = Chatbot.objects.filter(uuid=chatbot_uuid).first()
    if not chatbot.logo:
        chatbot.logo = "chatbot_logos/logo.jpg"
    if isinstance(chatbot.customization, str):
        customization = json.loads(chatbot.customization)
    else:
        customization = chatbot.customization
    formatted_prompts = "\n".join(chatbot.prompts)
    return render(request, 'ai_tools/customize_chatbot.html', {'current_chatbot':customization, 'chatbot':chatbot, 'prompts':formatted_prompts})

def chat_form(request):
    chat_uuid = request.GET.get('chat_uuid')
    chatbot_uuid = request.GET.get('chatbot_uuid')
    chat = ChatSession.objects.filter(uuid=chat_uuid).first()
    if chatbot_uuid:
        chatbot = Chatbot.objects.filter(uuid= chatbot_uuid).first()
        if chatbot is not None:
            welcome_message = chatbot.welcome_message
            if isinstance(chatbot.customization, str):
                customization = json.loads(chatbot.customization)
            else:
                customization = chatbot.customization
            prompts = json.dumps(chatbot.prompts)
        else:
            customization = dict
            prompts = dict

        return render(request, 'ai_tools/chat.html', {'current_chatbot':customization, 'prompts':prompts, 'chatbot':chatbot, 'welcome':welcome_message})
    else:
        if chat:
            chatbot = chat.chatbot
            if chatbot is not None:
                welcome_message = chatbot.welcome_message
                if isinstance(chatbot.customization, str):
                    customization = json.loads(chatbot.customization)
                else:
                    customization = chatbot.customization
                prompts = json.dumps(chatbot.prompts)
            else:
                customization = dict
                prompts = dict
                
            session_history_key = f'session_history_{chat.uuid}'
            request.session[f"{session_history_key}"] = chat.chat_history
            return render(request, 'ai_tools/chat.html', {'current_chatbot':customization, 'chat':chat, 'prompts':prompts, 'chatbot':chatbot, 'welcome':welcome_message})
        else:
            pass

def customize_bot(request):
    if request.method == 'POST':
        chatbot_uuid = request.POST.get('chatbot')
        prompts = request.POST.get('prompts')
        show_prompts = request.POST.get('show_prompts')
        welcome_message = request.POST.get('welcome_message')
        # Get the uploaded image file
        chatbot_logo = request.FILES.get('chatbot-logo')
        creativity = request.POST.get('creativity')
        # Construct customization data
        customization_data = {
            'font': request.POST.get('font'),
            'background_color': request.POST.get('background-color'),
            'font_color': request.POST.get('font-color'),
            'input_background': request.POST.get('input-background'),
            'chatbot_background_color': request.POST.get('chatbot-background-color'),
            'input_font_color': request.POST.get('input-font-color'),
            'user_background_color': request.POST.get('user-background-color'),
            'user_font_color': request.POST.get('user-font-color'),
            'prompts_font_color': request.POST.get('prompts-font-color'),
            'ai_tools_font_color': request.POST.get('ai-tools-font-color'),
            'ai_tools_border_color': request.POST.get('ai-tools-border-color'),
        }
        # Convert customization data to JSON
        chatbot_url = request.POST.get('chatbot-url')
        customization_json = json.dumps(customization_data)
        # Assuming 'customization_json' is your JSON string
        customization_data = json.loads(customization_json)

        # Now you can access the 'font' property


        # Update or create Chatbot instance with customization data
        chatbot = Chatbot.objects.filter(uuid=chatbot_uuid).first()
        if chatbot:
            # Handle image upload
            if chatbot_logo:
                # Save the uploaded image to your media directory
                chatbot.logo = chatbot_logo
                
            if chatbot_url:
                chatbot.custom_url = chatbot_url
            if prompts:
                lines = [line.strip() for line in prompts.splitlines() if line.strip()]
                chatbot.prompts = lines
            if show_prompts:
                if show_prompts == '0':
                    val = True
                else:
                    val = False
                chatbot.allow_prompts = val
            chatbot.creativity = creativity
            chatbot.welcome_message = welcome_message

            chatbot.customization = customization_json
            chatbot.save()

botbuilder/templates/ai_tools/ai_tools_home.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
<style>
.card-container {
    display: flex;
    justify-content: space-between;
    flex-wrap: wrap;
    gap: 20px; /* Optional: space between cards */
}

.chatbotBuilder__card {
    display: flex;
    flex-direction: column; /* Change to column to place icon above title */
    align-items: center;
    margin-bottom: 20px;
    padding: 20px;
    box-sizing: border-box;
    border-radius: 8px;
    background: #3f4156;
    position: relative; /* Added to make it a positioning context */
    text-decoration: none; /* Ensure the link does not have underlines */
    color: inherit; /* Inherit text color */
    width: 1000px;
    flex: 1; /* Ensure the cards take equal width */
}

.chatbotBuilder__card-icon {
    margin-bottom: 15px; /* Space between icon and text content */
    background: black;
    border-radius: 8px;
}

.chatbotBuilder__card-icon img {
    width: 350px; /* Adjust the size of the icon as needed */
    height: 300px;
    border-radius: 8px; /* Apply the same border-radius to the image */
}

.chatbotBuilder__card-title {
    margin: 0; /* Remove default margin */
    font-size: 18px;
    font-weight: bold;
    color: #ffffff;
}

.chatbotBuilder__card-description {
    margin: 5px 0 0 0; /* Adjust the margin for description */
    font-size: 14px;
    color: #d1d1d1;
}

/* Optional: Add hover effect for better user experience */
.chatbotBuilder__card:hover {
    background: #52536f; /* Slightly lighter background on hover */
}
</style>

<main class="layout layout--3">
  <div class="container">
    <!-- Topics Start -->
    <!-- Topics End -->

    <!-- Room List Start -->
    <div class="roomList">

      <div class="card-container">
        <a href="{% url 'ai_tools:chatbot_builder_home' %}" class="chatbotBuilder__card">
          <div class="chatbotBuilder__card-icon">
              <img src="{% static 'images/hero-bg.png' %}" alt="Icon" />
          </div>
          <div class="chatbotBuilder__card-content">
              <h3 class="chatbotBuilder__card-title">Chatbot Builder</h3>
              <p class="chatbotBuilder__card-description">Create and customize AI-powered chatbots with ease.</p>
          </div>
        </a>

        <!-- <a href="{% url 'ai_tools:photo_generator_home' %}" class="chatbotBuilder__card">
          <div class="chatbotBuilder__card-icon">
              <img src="{% static 'images/colorful_robot.png' %}" alt="Icon" />
          </div>
          <div class="chatbotBuilder__card-content">
              <h3 class="chatbotBuilder__card-title">AI Photo Generator</h3>
              <p class="chatbotBuilder__card-description">Create beautiful photos using AI to share with friends.</p>
          </div>
        </a> -->

      </div>
    </div>
  </div>
</main>

<!-- Include jQuery Library -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

{% endblock %}

botbuilder/templates/ai_tools/chatbot_builder_home.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
<style>
	/* Custom styles */
	body, html {
/*		height: 100%;*/
		margin: 0;
		display: flex;
		flex-direction: column;
		color:#000;
	}

	#main-content{
		width:100%
	}
	@media (max-width: 680px) {
	#main-content{
		position:fixed
	}
}
	
</style>

<div class="flex h-screen bg-gray-100" style="min-height: 88vh;">
	{% include 'ai_tools/sidebar.html' %}

	<!-- Main Content -->
	<div id="main-content" class="">
		<div class="lg:w-3/4 p-5 mt-5 mx-auto bg-white"> 
			<h2 class="text-4xl">Create Your First Chatbot</h2>
			<p class="my-5  p-5 border">Click on the '+' Icon on the left sidebar</p>
			</div>
	</div>

</div>
{% endblock %}

botbuilder/templates/ai_tools/chatbot_settings.html
<style type="text/css">
    td{
        padding: 20px!important;
        border-bottom: solid 1px;
    }
    th{
        text-align: left!important;
    }
</style>
<div class="bg-white lg:w-3/4 mx-auto p-5">
    <div class="flex" style="justify-content: space-around; align-items: center;">
        <h2 class="text-4xl my-4">{{ chatbot.name }} Settings</h2>
        <div class="flex">
            <form method="post" id="train_form" class="me-2">
                {% csrf_token %}
                <input type="hidden" name="chatbot_name" value="{{ chatbot.name }}">
                <button type="submit" class="bg-blue-900 text-white px-6 py-3 rounded-md btn train_btn">Retrain</button>
            </form>
            <button id="openModalBtn" class="bg-blue-900 text-white px-6 py-3 rounded-md btn me-2">Upload Files</button>
            <button id="delete_chatbot" class="bg-red-900 text-white px-6 py-3 rounded-md btn">Delete Chatbot</button>
        </div>
    </div>
    <div class="my-5">
        <table width="100%" class="table">
            <thead class="bg-gray-100">
                <th class="p-2">File Name</th>
                <th class="p-2">Upload Date</th>
                <th class="p-2">Delete</th>
            </thead>
            <tbody id="data-body">
                <!-- Data will be inserted here -->
            </tbody>
        </table>
    </div>
</div>

{% include 'ai_tools/loader.html' %}
{% include 'ai_tools/file_upload_modal.html' %}

<script type="text/javascript">
    $(document).ready(function(){
        // Show modal
        $('#openModalBtn').click(function() {
            $('#myModal').removeClass('hidden');
        });

        // Hide modal
        $('#closeModalBtn').click(function() {
            $('#myModal').addClass('hidden');
        });

        $('#train_form').submit(function(e){
            e.preventDefault();
            var formData = new FormData(this);
            console.log(formData)
            $.ajax({
                url: '{% url "ai_tools:train_bot" %}',
                type: 'POST',
                data: formData,
                processData: false,
                contentType: false,
                headers: {
                    'X-CSRFToken': '{{ csrf_token }}'
                },
                beforeSend: function(){
                    $('.train_btn').prop('disabled', true)
                    $('#loaderModal').removeClass('hidden');
                },
                success: function(response) {
                    $('.train_btn').prop('disabled', false)
                    $('#loaderModal').addClass('hidden');
                    swal.fire('Chatbot Trained Successfully', {
                        icon: "success",
                    })
                    
                },
                error: function(xhr, status, error) {
                    $('.train_btn').prop('disabled', false)
                    $('#loaderModal').addClass('hidden');
                    swal.fire(xhr.responseJSON.error, {
                        icon: "error",
                    });
                }
            })
        });


        var chatbot = $('#select-chatbot').val();
        $.ajax({
            url: '{% url "ai_tools:get_knowledge_base" %}',
            type: 'POST',
            data: {
                'chatbot' : chatbot,
                        'csrfmiddlewaretoken': '{{ csrf_token }}' // Add CSRF token for security
                    },
                    success: function(data) {
                        if (data.error) {
                            alert(data.error);
                        } else {
        $('#data-body').empty(); // Clear existing data
        if (data.urls != null) {
            data.urls.forEach(function(urlData) {
                var newRow = `
                <tr>
                <td class="p-2">${urlData.url}</td>
                <td class="p-2">${new Date(urlData.uploaded_at).toLocaleDateString('en-GB')}</td>
                <td class="p-2"><a href="#" class="delete-btn" data-url="${urlData.url}" data-file-path="${urlData.file_path}"><i class="fa fa-trash"></i></a></td>
                </tr>
                `;
                $('#data-body').append(newRow);
            });
        }
        if (data.files != null) {
            data.files.forEach(function(fileData) {
                var newRow = `
                <tr>
                <td class="p-2">${fileData.filename}</td>
                <td class="p-2">${new Date(fileData.uploaded_at).toLocaleDateString('en-GB')}</td>
                <td class="p-2"><a href="#" class="delete-btn" data-file-path="${fileData.file_path}"><i class="fa fa-trash"></i></a></td>
                </tr>
                `;
                $('#data-body').append(newRow);
            });
        }
    }
},
error: function(xhr, status, error) {
    console.error(error);
}
});


        $('#data-body').on('click', '.delete-btn', function() {
            var filePath = $(this).data('file-path');
            var url = $(this).data('url');
            var row = $(this).closest('tr');
            var chatbot_uuid = $('#select-chatbot').val();

            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.isConfirmed) {
                    $.ajax({
                url: '{% url "ai_tools:delete_knowledge_base_item" %}', // Update with your URL
                type: 'POST',
                data: {
                    'file_path': filePath || null,
                    'url': url || null,
                    'chatbot_uuid': chatbot_uuid,
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                success: function(response) {
                    if(response.success) {
                        row.fadeOut(500, function() {
                            $(this).remove();
                        });
                        Swal.fire(
                            'Deleted!',
                            'Your file has been deleted.',
                            'success'
                            );
                    } else {
                        Swal.fire(
                            'Error!',
                            'Error deleting item: ' + response.error,
                            'error'
                            );
                    }
                },
                error: function(xhr, status, error) {
                    console.error(error);
                    Swal.fire(
                        'Error!',
                        'Error deleting item.',
                        'error'
                        );
                }
            });
                }
            });
        });



        $('#delete_chatbot').click(function(){

            var chatbot_uuid = $('#select-chatbot').val();

            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.isConfirmed) {
                    $.ajax({
                url: '{% url "ai_tools:delete_chatbot" %}', // Update with your URL
                type: 'POST',
                data: {
                    'chatbot_uuid': chatbot_uuid,
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                success: function(response) {
                    Swal.fire(
                        'Deleted!',
                        'Your Chatbot has been deleted.',
                        'success'
                        );
                    location.reload();

                },
                error: function(xhr, status, error) {
                    console.error(error);
                    Swal.fire(
                        'Error!',
                        'Error deleting chatbot.',
                        'error'
                        );
                }
            });
                }
            });
        });

    });
</script>

botbuilder/templates/ai_tools/creativity_slider.html
<style>
    .slider {
        -webkit-appearance: none;
        appearance: none;
        width: 100%;
        height: 10px;
        background: #d3d3d3;
        outline: none;
        opacity: 0.7;
        -webkit-transition: .2s;
        transition: opacity .2s;
    }

    .slider:hover {
        opacity: 1;
    }

    .slider::-webkit-slider-thumb {
        -webkit-appearance: none;
        appearance: none;
        width: 25px;
        height: 25px;
        background: black;
        cursor: pointer;
        border-radius: 50%;
    }

    .slider::-moz-range-thumb {
        width: 25px;
        height: 25px;
        background: black;
        cursor: pointer;
        border-radius: 50%;
    }

    .slider-labels {
        display: flex;
        justify-content: space-between;
        margin-top: 10px;
    }
</style>

<div class="w-full">
        <input type="range" min="0" max="9" step="1" value="0" class="slider" id="slider" name="slider">
        <div class="slider-labels px-5">
            <span id="middle-label">1</span>
            <span id="end-label">2</span>
            <span id="middle-label">3</span>
            <span id="end-label">4</span>
            <span id="middle-label">5</span>
            <span id="end-label">6</span>
            <span id="middle-label">7</span>
            <span id="end-label">8</span>
            <span id="middle-label">9</span>
            <span id="middle-label">10</span>
        </div>
</div>

botbuilder/templates/ai_tools/export_chat.html
<div class="lg:w-3/4 mx-auto bg-white p-5">
    <h2 class="text-4xl">Export Chat Records</h2>
    <p class="mt-2">Export chat conversations effortlessly.</p>

    <div class="p-5 mt-5 border rounded-md">
        <button id="export-btn" class="btn bg-gray-800 text-white">Export</button>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('#export-btn').click(function() {
            var chatbot_uuid = $('#select-chatbot').val();
            $.ajax({
                    type: 'POST',
                    url: '{% url 'ai_tools:export_chats' %}',
                    data: {
                        'chatbot_uuid': chatbot_uuid,
                        'csrfmiddlewaretoken': '{{ csrf_token }}'
                    },
                    xhrFields: {
                        responseType: 'blob'
                    },
                    success: function(response) {
                        console.log('Successful');
                        var link = document.createElement('a');
                        link.href = window.URL.createObjectURL(response);
                        link.download = 'chat_sessions.zip';
                        document.body.appendChild(link);
                        link.click();
                        document.body.removeChild(link);
                    },
                    error: function(error) {
                        console.error('Error:', error);
                        // Handle errors if needed
                    }
                });
            });
        });
    </script>

botbuilder/templates/ai_tools/loader.html
<div id="loaderModal" class="fixed inset-0 flex items-center justify-center bg-gray-800 bg-opacity-50 hidden p-5">
    <div class="flex flex-col items-center bg-white p-4 rounded-lg shadow-lg p-5">
        <p class="mb-4 text-lg font-semibold text-gray-700 p-5">This can take a few minutes...</p>
        <div class="loader border-t-4 border-blue-500 rounded-full w-16 h-16 animate-spin p-5"></div>
    </div>
</div>

<style>
    #loaderModal{
        z-index: 10000000;
    }
</style>

botbuilder/templates/ai_tools/photo_generator_home.html
{% extends 'main.html' %}
{% load static %}
{% block content %}






{% endblock %}